services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Shopsys\ProductFeed\HeurekaDeliveryBundle\HeurekaDeliveryFeedConfig:
    tags:
      - { name: shopsys.product_feed, type: delivery }
