services:
  shopsys.product_feed.heureka_delivery_bundle.feed_config:
    class: Shopsys\ProductFeed\HeurekaDeliveryBundle\HeurekaDeliveryFeedConfig
    tags:
      - { name: shopsys.product_feed, type: delivery }
